mt5:
  server: ""            # optional (leave empty if local terminal)
  login: 5040745538             # set your login id
  password: "LfJdNv_3"          # set your password
  port: null              # optional
  from: "2025-09-1 00:00"  #history start
  to: "2025-09-30 00:00"  #history end

data:
  symbol_a: "GBPUSD"
  symbol_b: "EURUSD"
  timeframe: "M1"

strategy:
  regression_period: 252
  lookback_period: 20
  entry_z: 2.4
  stop_z: 4.8   #if using sl_Zscore
  takeprofit_z: 4.8   #if using tp_Zscore
  risk_percent: 1.0    #will be used by optuna method
  tp_multiple: 2.0
  min_correlation: 0.2
  sl_type: "SL_ZScore"        # SL_ZScore or SL_Percent
  tp_type: "TP_Multiple"      # TP_Multiple or TP_ZScore
  stoploss_percent: 2.5
  max_lots: 5.0

execution:
  latency_ms: 221
  slippage_std_points: 0.25   # slippage model (std dev in units of sigma of spread)
  commission_per_trade: 0.0

optimizer:
  method: "grid"   # either grid or optuna. grd tests across all parameter combinations
  objective: "sharpe"
  walk_forward_splits: 15
  train_days: 1
  test_days: 1
  n_jobs: 12
  seed: 42


optimize:    #defines which parameters to optimize
  entry_z: {start: 0.0, stop: 10.0, step: 0.1}
  stop_z: {start: 0.5, stop: 10.0, step: 0.1}
  #takeprofit_z: {start: 0.0, stop: 10.0, step: 0.5}

output:
  save_dir: "./results"
  export_set_file: true
  top_k: 5
